### ISSUE TITLE
Please update to gnome 45

### ISSUE THREAD

**Issue by dmnmsc** [jqno/gnome-happy-appy-hotkey#2]
This extensions needs an update. Incompatibility with gnome 45.

**Comment by jqno** [comment]
I know. I hope to get to it soon, but my distro is still on 44 so I can't easily test. PRs are welcome though 😉

**Comment by dmnmsc** [comment]
Yep. Sorry. I'm not a techie guy. I tried updating manifest to "45". After system restart I get 

```
SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  @file:///home/dmnmsc/.local/share/gnome-shell/extensions/happy-appy-hotkey@jqno.nl/prefs.js:2:24
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```

**Comment by jqno** [comment]
Yeah, they changed some things around so I really have to sit down for it.

What distro do you use? Maybe I can load that in a VM to do some testing.

**Comment by dmnmsc** [comment]
Thank you very much. I'm using RebornOS (Arch)

**Comment by jqno** [comment]
I've just published a new version that should support Gnome 45. Please let me know if you have any issues with it, because I've only been able to test it in a VM so far :).

**Comment by dmnmsc** [comment]
Thank you very much! I can confirm the extension is working as expected.

**Comment by jqno** [comment]
Nice! Thanks for the follow-up
