### ISSUE TITLE
Terminal 'foot' not working

### ISSUE THREAD

**Issue by quesada** [jqno/gnome-happy-appy-hotkey#3]
Foot is a much faster terminal compared to gnome terminal, a worthy upgrade. 

However, when using it with Happy Appy, it always launches a new window instead of focusing the existing one (?).

To reproduce, install foot (should be on your distro), assign a hotkey to it. Launch it once (see new window), Press key again: should focus existing window but it creates a new one.

**Comment by jqno** [comment]
I use Kitty myself, so I haven't encountered this issue before.
I installed Foot, but for me things seem to work as expected. I did notice that it creates three launchers on my system (Foot, Foot Client and Foot Server). Maybe I'm using the wrong one?

**Comment by quesada** [comment]
Which one are you using? For me it launches a new window everytime, never reusing an existing one?

**Comment by jqno** [comment]
I understand the problem, I've seen it when I was debugging when I initially but the extension, but I haven't seen it anymore since I released it.

I was using the "Foot" launcher. Should I be using any of the others?

**Comment by quesada** [comment]
I abandoned foot and used kitty as you do. So we can close this :)

**Comment by jqno** [comment]
Ah, thanks for the update :)
I'm not very savvy with developing Gnome plugins (I made this one to scratch my own itch), and since Foot only works on Wayland, and testing Gnome plugins is way more difficult on Wayland than X, debugging this issue would have been quite hard. So I'm glad it's no longer necessary :)
