### ISSUE TITLE
Hotkeys available don't include scrolllock, pause, altGr etc

### ISSUE THREAD

**Issue by quesada** [jqno/gnome-happy-appy-hotkey#4]
... and it just happens they are mighty convenient in the keyboard I'm using (maltron) to launch apps :) 

Is it possible to handle those few, or would it imply a lot of work to add them?

Thanks, amazing extension!

**Comment by jqno** [comment]
I hadn't considered these buttons, I will look into it. Might take a bit though, because I'll be away from my computer for a few days.

Do you mean AltGr as a standalone button, or in combination with some other key?

**Comment by quesada** [comment]
Standalone. Thanks!

**Comment by jqno** [comment]
This should now be live; you may need to log out and back in.
I've explicitly added Pause and ScrollLock to the allowed hotkeys (Gnome disallows them by default).

Unfortunately I was unable to do the same for AltGr, as it's not handled as a separate button, but is normally used in combination with other keys. This makes it very hard to detect, while also still detecting any key combinations made with AltGr. If you don't use AltGr to compose characters, you may be able to bind that key to something else...
