### ISSUE TITLE
[Feature request] Limit the window list to rotate through to existing desktop

### ISSUE THREAD

**Issue by quesada** [jqno/gnome-happy-appy-hotkey#6]
I use a notetaking app with multiple windows open, and rotate using Happy Appy's single key presses. Wonderful workflow.

Except that if I want to use workspaces (Gnome, KDE, but mostly every desktop supports them; they are a basic unix desktop concept at this point)... it teleports away from my current workspace. This is most of the time something I don't want.

Can this be an option, perhaps?

**Comment by quesada** [comment]
For context, before Wayland made it broken, I used Jumpapp and wmctrl.

https://man.archlinux.org/man/wmctrl.1.en

wmctrl has the concept of desktops. Jumpapp uses it to find, list windows. I suspect the Gnome API you might be using has that concept too.

**Comment by jqno** [comment]
Yeah, Gnome should be able to do that too.

Just to be clear, do you want this feature only for the 'unbound cycle' hotkey, or for all of them?

In case you want it for all hotkeys, what should happen if you have an app open on another workspace and you press its key? Should it start a new instance on the current workspace, or ignore the keypress?

**Comment by quesada** [comment]
For all apps. And it should start a new app. This is my workflow

**Comment by jqno** [comment]
Ah, I see. My workflow is quite different, but I see the value in yours, so I can definitely add that option. Can't promise when though, because of work and family commitments.

**Comment by jqno** [comment]
I've just released a new version with this feature. There's now a checkbox in the settings. If you enable it, you should get the behaviour you're looking for.
