### ISSUE TITLE
Feature Request: ability to export and import hotkeys

### ISSUE THREAD

**Issue by dmnmsc** [jqno/gnome-happy-appy-hotkey#7]
I use more than one computer and I'd like to have the same shortcuts in both of them.

I miss an option to export and import shortcuts

**Comment by jqno** [comment]
Good point. Fortunately, Gnome already has a program called `dconf` for this.

Open a terminal and run this command:

```sh
dconf dump /org/gnome/shell/extensions/happy-appy-hotkey/ > happy-appy-hotkey-settings.dconf
```

You can save the `happy-appy-hotkey-settings.dconf` file somewhere safe. When you need to import them again, you can run this:

```sh
dconf load /org/gnome/shell/extensions/happy-appy-hotkey/ < happy-appy-hotkey-settings.dconf
```

Your settings should take effect immediately.

I've added this to the readme as well, so other people can benefit too.

**Comment by dmnmsc** [comment]
That's true! But maybe an option in the GUI settings would make the process easier for non-techie people. 

Anyway, thanks for the tip!

**Comment by jqno** [comment]
True, that would certainly be nice to have, but I'm afraid I won't be able to get to it any time soon, sorry about that...

**Comment by dmnmsc** [comment]
Don't worry! This extension made my day, month and year. Thank you very much!

**Comment by jqno** [comment]
I'm happy to hear that by scratching my own itch, I've also been able to help you! 😄
