### ISSUE TITLE
Raising window is not the first one

### ISSUE THREAD

**Issue by Pierre-Thibault** [jqno/gnome-happy-appy-hotkey#9]
Current behaviour: When raising a window, it does necessarily pick the front most window available.

Expected behaviour: Front most window available should be picked.

**Comment by jqno** [comment]
Good idea, I never realised this was something that annoyed me, but now you mentioned it, I realised that it does 😅
I just published an update with this feature.

**Comment by Pierre-Thibault** [comment]
Wonderful. 😃 I realized that my description was missing the word "not" in its first sentence. So, you made me realized a bug in my bug description.
